export const CHANGEBANNERS = 'CHANGE_BANNERS'
export const CHANGEHOTRECOMMEND = 'CHANGE_HOT_RECOMMEND'

export const CHANGENEWALBUM = 'CHANGE_NEW_ALBUM'
export const CHANGEUPRANKING = 'CHANGE_UP_RANKING'
export const CHANGENEWRANKING = 'CHANGE_NEW_RANKING'
export const CHANGEORIGINALRANKING = 'CHANGE_ORIGINAL_RANKING'